theme: jekyll-theme-slate

title: Hurricane Analysis
description: A Bayesian analysis of hurricane data from the National Hurricane Center.

markdown: kramdown

exclude:
  - _layouts
  - _includes
  - app